version: '3'

services:

  fits:
    build:
      context: .
      dockerfile: ./fits/Dockerfile
    container_name: fits
    env_file: .env
    networks:
      - web
    restart: unless-stopped
    ports:
      - 8081:8080

  rest:
    container_name: rest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    networks:
      - web
    restart: unless-stopped
    ports:
      - 8082:8080
    depends_on:
      - fits
      - db-docker

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: web
    env_file: .env
    networks:
      - web
    restart: unless-stopped
    ports:
      - 8080:3000

  db-docker:
    image: oscarfonts/h2
    container_name: db-docker
    env_file: .env
    environment:
      - H2_OPTIONS=-ifNotExists
    networks:
      - web
    restart: unless-stopped
    ports:
      - 1521:1521
      - 81:81

networks:
  web: